#! /bin/bash

format="%Y-%m-%d"
mooddir="$HOME/mood-journal/"

if [[ "$1" = "tree" ]]; then
    lsd --tree $mooddir
    exit
fi
if [[ -z "$1" ]]; then
    filedate=$(date +$format)
else
    filedate=$(date -d "$@" +$format)
fi

filename="$mooddir$filedate.md"

if [[ ! -f "$filename" ]]; then
    cp ~/Templates/mood-journal-template.md "$filename"
    sed "s/date:/date: $filedate/g" -i $filename
fi

$EDITOR "$filename"

